root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main.exe ./cmd/api/main.go"
  bin = "tmp/main.exe"
  full_bin = "./tmp/main.exe"
  delay = 1000
  rerun_delay = 500
  log = "build-errors.log"

  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "bin"]
  exclude_regex = ["_test.go"]

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
enabled = false
app_port = 0
proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
