version: '3.8'

services:
  db:
    image: postgres:17.3
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U youruser -d yourdb || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://youruser:yourpassword@db:5432/yourdb
      GIN_MODE: release
      HOST: true
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

volumes:
  pg_data:

networks:
  app-network:
