version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network


  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://yourusername:yourpassword@db:5432/yourdatabase
      GIN_MODE: release
    depends_on:
      - db
    networks:
      - app-network

volumes:
  pg_data:

networks:
  app-network:
