version: '3.8'

x-db-env: &common-db-env
  POSTGRES_USER: myuser
  POSTGRES_PASSWORD: mypassword
  POSTGRES_DB: mydatabase

x-api-env: &common-api-env
  DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
  GIN_MODE: release
  HOST: true # true = 0.0.0.0 (recommended) // false = localhost


services:
  db:
    image: postgres
    environment:
      <<: *common-db-env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      retries: 5
      start_period: 10s

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      <<: *common-api-env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

volumes:
  pg_data:

networks:
  app-network:
